<?php

return [
    // Validation générales
    'required' => 'Ce champ est obligatoire.',
    'min' => 'Ce champ doit contenir au moins :min caractères.',
    'max' => 'Ce champ doit contenir au plus :max caractères.',
    'email' => 'Adresse email invalide.',
    'unique' => 'Cette valeur est déjà utilisée.',
    'date' => 'Date invalide.',
    'phone' => 'Le numéro de téléphone doit commencer par 70, 76, 77 ou 78 suivi de 7 chiffres.',
    'matricule' => 'Format de matricule invalide.',
    'password' => 'Le mot de passe doit contenir au moins 8 caractères, une majuscule et un chiffre.',
    'date.format' => 'Format de date invalide. Utilisez le format JJ/MM/AAAA.',
    'date.chronologie' => 'La date de début doit être antérieure à la date de fin.',
    
    // Authentification
    'login.invalide' => 'Email, matricule ou mot de passe incorrect.',
    'login.required' => 'Veuillez saisir votre email ou matricule.',
    'password.required' => 'Veuillez saisir votre mot de passe.',
    'password.reset.email_sent' => 'Si cette adresse existe dans notre système, un email de réinitialisation vous sera envoyé.',
    'password.reset.token_invalid' => 'Le lien de réinitialisation est invalide ou a expiré.',
    'password.reset.success' => 'Votre mot de passe a été réinitialisé avec succès.',
    'password.confirm.mismatch' => 'Les mots de passe ne correspondent pas.',
    'account.locked' => 'Votre compte a été temporairement verrouillé suite à plusieurs tentatives de connexion.',
    'forgot.email.invalid' => 'Veuillez saisir une adresse email valide.',
    'forgot.email.inexistant' => 'Aucun compte associé à cette adresse email.',
    'reset.password.length' => 'Le mot de passe doit contenir au moins 8 caractères.',
    'reset.password.majuscule' => 'Le mot de passe doit contenir au moins une lettre majuscule.',
    'reset.password.chiffre' => 'Le mot de passe doit contenir au moins un chiffre.',
    'reset.failed' => 'Une erreur est survenue lors de la réinitialisation du mot de passe.',

    // Photo
    'photo.required' => 'La photo est requise.',
    'photo.format' => 'La photo doit être au format JPG ou PNG.',
    'photo.size' => 'La photo ne doit pas dépasser 2 Mo.',
    
    // Promotion
    'promotion.nom.required' => 'Le nom de la promotion est requis.',
    'promotion.nom.existe' => 'Une promotion avec ce nom existe déjà.',
    'promotion.date_debut.required' => 'La date de début est requise.',
    'promotion.date_debut.format' => 'Le format de la date de début est invalide. Utilisez le format JJ/MM/AAAA.',
    'promotion.date_fin.required' => 'La date de fin est requise.',
    'promotion.date_fin.format' => 'Le format de la date de fin est invalide. Utilisez le format JJ/MM/AAAA.',
    'promotion.date_fin.chronologie' => 'La date de fin doit être postérieure à la date de début.',
    'promotion.referentiels.required' => 'Au moins un référentiel doit être sélectionné.',
    
    // Référentiel
    'referentiel.nom.required' => 'Le nom du référentiel est requis.',
    'referentiel.nom.existe' => 'Un référentiel avec ce nom existe déjà.',
    'referentiel.description.required' => 'La description est requise.',
    'referentiel.capacite.required' => 'La capacité est requise.',
    'referentiel.capacite.numeric' => 'La capacité doit être un nombre positif.',
    'referentiel.sessions.required' => 'Le nombre de sessions est requis.',
    'referentiel.existe.dans.promo' => 'Ce référentiel est déjà associé à la promotion.',

    // Apprenant
    'apprenant.nom.required' => 'Le nom est obligatoire.',
    'apprenant.nom.max' => 'Le nom ne doit pas dépasser 50 caractères.',
    'apprenant.prenom.required' => 'Le prénom est obligatoire.',
    'apprenant.prenom.max' => 'Le prénom ne doit pas dépasser 50 caractères.',
    'apprenant.date_naissance.required' => 'La date de naissance est obligatoire.',
    'apprenant.date_naissance.format' => 'Le format de la date de naissance est invalide. Utilisez le format JJ/MM/AAAA.',
    'apprenant.date_naissance.invalide' => 'La date de naissance est invalide.',
    'apprenant.lieu_naissance.required' => 'Le lieu de naissance est obligatoire.',
    'apprenant.lieu_naissance.max' => 'Le lieu de naissance ne doit pas dépasser 100 caractères.',
    'apprenant.adresse.required' => 'L\'adresse est obligatoire.',
    'apprenant.adresse.max' => 'L\'adresse ne doit pas dépasser 200 caractères.',
    'apprenant.email.required' => 'L\'email est obligatoire.',
    'apprenant.email.invalid' => 'L\'email est invalide.',
    'apprenant.email.exists' => 'L\'email existe déjà.',
    'apprenant.telephone.required' => 'Le téléphone est obligatoire.',
    'apprenant.telephone.format' => 'Le numéro de téléphone doit commencer par 70, 76, 77 ou 78 suivi de 7 chiffres.',
    'apprenant.referentiel.required' => 'Le référentiel est obligatoire.',
    'apprenant.photo.required' => 'La photo est obligatoire.',
    'apprenant.photo.format' => 'La photo doit être au format JPG ou PNG.',
    'apprenant.photo.size' => 'La photo ne doit pas dépasser 2 Mo.',
    'apprenant.tuteur.nom.required' => 'Le nom du tuteur est obligatoire.',
    'apprenant.tuteur.nom.max' => 'Le nom du tuteur ne doit pas dépasser 100 caractères.',
    'apprenant.tuteur.lien.required' => 'Le lien de parenté est obligatoire.',
    'apprenant.tuteur.lien.max' => 'Le lien de parenté ne doit pas dépasser 50 caractères.',
    'apprenant.tuteur.adresse.required' => 'L\'adresse du tuteur est obligatoire.',
    'apprenant.tuteur.adresse.max' => 'L\'adresse du tuteur ne doit pas dépasser 200 caractères.',
    'apprenant.tuteur.telephone.required' => 'Le téléphone du tuteur est obligatoire.',
    'apprenant.tuteur.telephone.format' => 'Le numéro de téléphone du tuteur doit commencer par 70, 76, 77 ou 78 suivi de 7 chiffres.',
    'apprenant.matricule.generated' => 'Le matricule est généré automatiquement.',
];